package com.claroinvestments.bsestarmf.payments;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2020-03-03T11:20:30.820+05:30
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IStarMFPaymentGatewayService")
@XmlSeeAlso({ObjectFactory.class})
public interface IStarMFPaymentGatewayService {

    @WebMethod(operationName = "PaymentGatewayAPI", action = "http://tempuri.org/IStarMFPaymentGatewayService/PaymentGatewayAPI")
    @Action(input = "http://tempuri.org/IStarMFPaymentGatewayService/PaymentGatewayAPI", output = "http://tempuri.org/IStarMFPaymentGatewayService/PaymentGatewayAPIResponse")
    @RequestWrapper(localName = "PaymentGatewayAPI", targetNamespace = "http://tempuri.org/", className = "com.claroinvestments.bsestarmf.payments.PaymentGatewayAPI")
    @ResponseWrapper(localName = "PaymentGatewayAPIResponse", targetNamespace = "http://tempuri.org/", className = "com.claroinvestments.bsestarmf.payments.PaymentGatewayAPIResponse")
    @WebResult(name = "PaymentGatewayAPIResult", targetNamespace = "http://tempuri.org/")
    public com.claroinvestments.bsestarmf.payments.Response paymentGatewayAPI(
        @WebParam(name = "Param", targetNamespace = "http://tempuri.org/")
        com.claroinvestments.bsestarmf.payments.RequestParam param
    );

    @WebMethod(operationName = "GetPassword", action = "http://tempuri.org/IStarMFPaymentGatewayService/GetPassword")
    @Action(input = "http://tempuri.org/IStarMFPaymentGatewayService/GetPassword", output = "http://tempuri.org/IStarMFPaymentGatewayService/GetPasswordResponse")
    @RequestWrapper(localName = "GetPassword", targetNamespace = "http://tempuri.org/", className = "com.claroinvestments.bsestarmf.payments.GetPassword")
    @ResponseWrapper(localName = "GetPasswordResponse", targetNamespace = "http://tempuri.org/", className = "com.claroinvestments.bsestarmf.payments.GetPasswordResponse")
    @WebResult(name = "GetPasswordResult", targetNamespace = "http://tempuri.org/")
    public com.claroinvestments.bsestarmf.payments.Response getPassword(
        @WebParam(name = "Param", targetNamespace = "http://tempuri.org/")
        com.claroinvestments.bsestarmf.payments.PasswordRequest param
    );
}
