package dev.anshumax.bsestarmf.additionalservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-25T10:31:09.658+05:30
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://www.bsestarmf.in/2016/01/", name = "IStarMFWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface IStarMFWebService {

    @WebMethod(operationName = "EMandateAuthURL", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/EMandateAuthURL")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/EMandateAuthURL", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/EMandateAuthURLResponse")
    @RequestWrapper(localName = "EMandateAuthURL", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.EMandateAuthURL")
    @ResponseWrapper(localName = "EMandateAuthURLResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.EMandateAuthURLResponse2")
    @WebResult(name = "EMandateAuthURLResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public EMandateAuthURLResponse eMandateAuthURL(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        EMandateAuthURLRequest param
    );

    @WebMethod(operationName = "ProvOrderStatus", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/ProvOrderStatus")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/ProvOrderStatus", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/ProvOrderStatusResponse")
    @RequestWrapper(localName = "ProvOrderStatus", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.ProvOrderStatus")
    @ResponseWrapper(localName = "ProvOrderStatusResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.ProvOrderStatusResponse")
    @WebResult(name = "ProvOrderStatusResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public ProvOrderResponse provOrderStatus(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        OrderRequest param
    );

    @WebMethod(operationName = "GetAccessToken", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetAccessToken")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetAccessToken", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetAccessTokenResponse")
    @RequestWrapper(localName = "GetAccessToken", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.GetAccessToken")
    @ResponseWrapper(localName = "GetAccessTokenResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.GetAccessTokenResponse")
    @WebResult(name = "GetAccessTokenResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public Response getAccessToken(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        PasswordRequest param
    );

    @WebMethod(operationName = "AOFPanSearch", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/AOFPanSearch")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/AOFPanSearch", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/AOFPanSearchResponse")
    @RequestWrapper(localName = "AOFPanSearch", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.AOFPanSearch")
    @ResponseWrapper(localName = "AOFPanSearchResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.AOFPanSearchResponse2")
    @WebResult(name = "AOFPanSearchResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public AOFPanSearchResponse aofPanSearch(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        AOFPanSearchRequest param
    );

    @WebMethod(operationName = "GetPasswordMobile", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordMobile")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordMobile", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordMobileResponse")
    @RequestWrapper(localName = "GetPasswordMobile", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.GetPasswordMobile")
    @ResponseWrapper(localName = "GetPasswordMobileResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.GetPasswordMobileResponse")
    @WebResult(name = "GetPasswordMobileResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public Response getPasswordMobile(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        PasswordRequest param
    );

    @WebMethod(operationName = "GetPasswordForChildOrder", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordForChildOrder")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordForChildOrder", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/GetPasswordForChildOrderResponse")
    @RequestWrapper(localName = "GetPasswordForChildOrder", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.GetPasswordForChildOrder")
    @ResponseWrapper(localName = "GetPasswordForChildOrderResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.GetPasswordForChildOrderResponse")
    @WebResult(name = "GetPasswordForChildOrderResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public Response getPasswordForChildOrder(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        PasswordRequest param
    );

    @WebMethod(operationName = "ChildOrderDetails", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/ChildOrderDetails")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/ChildOrderDetails", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/ChildOrderDetailsResponse")
    @RequestWrapper(localName = "ChildOrderDetails", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.ChildOrderDetails2")
    @ResponseWrapper(localName = "ChildOrderDetailsResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.ChildOrderDetailsResponse")
    @WebResult(name = "ChildOrderDetailsResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public ChildOrderResponse childOrderDetails(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        ChildOrderRequest param
    );

    @WebMethod(operationName = "MFAPIMobile", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPIMobile")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPIMobile", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPIMobileResponse")
    @RequestWrapper(localName = "MFAPIMobile", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.MFAPIMobile")
    @ResponseWrapper(localName = "MFAPIMobileResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.MFAPIMobileResponse")
    @WebResult(name = "MFAPIMobileResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public Response mfapiMobile(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        MFAPIRequest param
    );

    @WebMethod(action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/getPassword")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/getPassword", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/getPasswordResponse")
    @RequestWrapper(localName = "getPassword", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.GetPassword")
    @ResponseWrapper(localName = "getPasswordResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.GetPasswordResponse")
    @WebResult(name = "getPasswordResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public java.lang.String getPassword(
        @WebParam(name = "UserId", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String userId,
        @WebParam(name = "MemberId", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String memberId,
        @WebParam(name = "Password", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String password,
        @WebParam(name = "PassKey", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String passKey
    );

    @WebMethod(operationName = "OrderStatus", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/OrderStatus")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/OrderStatus", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/OrderStatusResponse")
    @RequestWrapper(localName = "OrderStatus", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.OrderStatus")
    @ResponseWrapper(localName = "OrderStatusResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.OrderStatusResponse")
    @WebResult(name = "OrderStatusResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public OrderResponse orderStatus(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        OrderRequest param
    );

    @WebMethod(operationName = "MFAPI", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPI")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPI", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MFAPIResponse")
    @RequestWrapper(localName = "MFAPI", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.MFAPI")
    @ResponseWrapper(localName = "MFAPIResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.MFAPIResponse")
    @WebResult(name = "MFAPIResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public java.lang.String mfapi(
        @WebParam(name = "Flag", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String flag,
        @WebParam(name = "UserId", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String userId,
        @WebParam(name = "EncryptedPassword", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String encryptedPassword,
        @WebParam(name = "param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        java.lang.String param
    );

    @WebMethod(operationName = "MandateDetails", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MandateDetails")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MandateDetails", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/MandateDetailsResponse")
    @RequestWrapper(localName = "MandateDetails", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.MandateDetails2")
    @ResponseWrapper(localName = "MandateDetailsResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.MandateDetailsResponse2")
    @WebResult(name = "MandateDetailsResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public MandateDetailsResponse mandateDetails(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        MandateDetailsRequest param
    );

    @WebMethod(operationName = "AllotmentStatement", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/AllotmentStatement")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/AllotmentStatement", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/AllotmentStatementResponse")
    @RequestWrapper(localName = "AllotmentStatement", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.AllotmentStatement")
    @ResponseWrapper(localName = "AllotmentStatementResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.AllotmentStatementResponse2")
    @WebResult(name = "AllotmentStatementResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public AllotmentStatementResponse allotmentStatement(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        AllotmentStatementRequest param
    );

    @WebMethod(operationName = "RedemptionStatement", action = "http://www.bsestarmf.in/2016/01/IStarMFWebService/RedemptionStatement")
    @Action(input = "http://www.bsestarmf.in/2016/01/IStarMFWebService/RedemptionStatement", output = "http://www.bsestarmf.in/2016/01/IStarMFWebService/RedemptionStatementResponse")
    @RequestWrapper(localName = "RedemptionStatement", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.RedemptionStatement")
    @ResponseWrapper(localName = "RedemptionStatementResponse", targetNamespace = "http://www.bsestarmf.in/2016/01/", className = "com.claroinvestments.bsestarmf.starmfservice.RedemptionStatementResponse2")
    @WebResult(name = "RedemptionStatementResult", targetNamespace = "http://www.bsestarmf.in/2016/01/")
    public RedemptionStatementResponse redemptionStatement(
        @WebParam(name = "Param", targetNamespace = "http://www.bsestarmf.in/2016/01/")
        RedemptionStatementRequest param
    );
}
